Feature/lists
sawyre/ru-study-python pull request #1
Opened 2023-08-30 16:20 UTC by sawyre

2023-09-01 19:32 UTC, aleksandr-semenov-dbp requested changes

2023-09-01 19:32 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        while right_border - left_border > 1:
по условию надо сделать рекурсивно

2023-09-01 21:31 UTC, sawyre commented on lists/lists.py
> +        while right_border - left_border > 1:
Здравствуйте, поправил, спасибо!

2023-09-09 19:58 UTC, aleksandr-semenov-dbp approved these changes

2023-09-10 06:25 UTC, merged