Feature/filter map
sawyre/ru-study-python pull request #3
Opened 2023-08-30 19:46 UTC by sawyre

2023-09-01 19:37 UTC, aleksandr-semenov-dbp requested changes

2023-09-01 19:37 UTC, aleksandr-semenov-dbp commented on filter_map/filter_map.py
> +            lambda res, elem: (res + [func(elem)[1]]) if func(elem)[0] else res, input_array, []
функция вызывается дважды для подходящих элементов, это плохо

2023-09-01 19:37 UTC, aleksandr-semenov-dbp commented on filter_map/filter_map.py
> +            lambda res, elem: (res + [func(elem)[1]]) if func(elem)[0] else res, input_array, []
видимо сбивает комментарий по mapreduce в задании, но самом деле в данном случае он не нужен, нужно простое решение

2023-09-05 14:12 UTC, sawyre commented on filter_map/filter_map.py
> +            lambda res, elem: (res + [func(elem)[1]]) if func(elem)[0] else res, input_array, []
Здравствуйте, переписал на простое решение.

2023-09-19 07:35 UTC, merged