Feature/flask exercises
sawyre/ru-study-python pull request #4
Opened 2023-09-10 09:36 UTC by sawyre

Здравствуйте,

При выполнении этого задания возникло пару вопросов:

1.  test_unprocessable_entity - пришлось поправить эту функцию, так как во всех остальных при проверке бралось response.get_json, а в этой функции, почему то проверялось равенство просто response. Или там можно передать errors каким-то другим способом, а не как json?
2.  Я пробовал создать словарь пользователей на уровне класса, чтобы все данные сохранялись, но тесты, как я понял, подразумевают полную независимость. Поэтому я добавил создание словаря на уровень create_user, что вероятно не очень правильно. Может можно на уровне тестов обновлять контекст вместе со словарем?

P.S. Случайно создал merge в основной репозиторий, извиняюсь.

2023-09-11 07:20 UTC, aleksandr-semenov-dbp requested changes

2023-09-11 07:20 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +        FlaskExercise.users = {}
это надо бы вынести все-таки на уровень класса. ничего сломаться не должно, а все эндпоинты будут работать и без create_user()

2023-09-11 07:20 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +        else:
если if заканчивается return, else писать не надо, это уменьшает количество отступов и легче читается

2023-09-11 07:20 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +        if name in FlaskExercise.users:
если одна из веток состоит только из return, то стоит сформулировать условие так, чтобы она шла впереди многооператорной и с учетом предыдущего коммента получается легче читаемый код

2023-09-11 07:20 UTC, aleksandr-semenov-dbp commented on flask_exercises/test_flask_excercises.py
> +        assert response.get_json() == {"errors": {"name": "This field is required"}}
Здесь все правильно сделал, так работало в старых версиях фласка, и мы специально оставили эту ошибку для исправления

2023-09-11 07:20 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +        if "name" in json_data and json_data["name"] not in FlaskExercise.users:
здесь тоже бы перфакторить с учетом других коментов

2023-09-14 12:58 UTC, sawyre commented on flask_exercises/flask_excercises.py
> +        FlaskExercise.users = {}
Перенес. Можно у вас узнать, сейчас тесты являются в некоторой степени зависимыми друг от друга, так как работают с одним словарем. Можно в теории запустить их независимо по очереди по отдельности. Также можно сделать явную очистку массива в начале теста. Но это выглядит как небольшие костыли. В связи с этим возникает вопрос: Можно ли вообще использовать зависимые тесты или это плохой тон и нужно поискать способ как их запустить, каждый в своем собственном контексте?
Заранее спасибо за ответ.

2023-09-14 13:00 UTC, sawyre commented on flask_exercises/flask_excercises.py
> +        else:
Спасибо, поправил

2023-09-14 13:01 UTC, sawyre commented on flask_exercises/flask_excercises.py
> +        if name in FlaskExercise.users:
Спасибо, поправил

2023-09-14 13:01 UTC, sawyre commented on flask_exercises/test_flask_excercises.py
> +        assert response.get_json() == {"errors": {"name": "This field is required"}}
Принял, спасибо!

2023-09-14 13:01 UTC, sawyre commented on flask_exercises/flask_excercises.py
> +        if "name" in json_data and json_data["name"] not in FlaskExercise.users:
Поправил!

2023-09-18 12:11 UTC, aleksandr-semenov-dbp commented on flask_exercises/flask_excercises.py
> +        FlaskExercise.users = {}
Ты прав конечно же, тесты надо писать независимыми, обычно тестовые функции зависят от состояния БД, которое pytest сбрасывает автоматически. Здесь - да, при такой эмуляции БД она не сбрасывается, и вообще говоря это неправильно, но для этого упражнения я предлагаю оставить так.

2023-09-18 12:11 UTC, aleksandr-semenov-dbp approved these changes

2023-09-19 07:34 UTC, sawyre commented on flask_exercises/flask_excercises.py
> +        FlaskExercise.users = {}
Спасибо

2023-09-19 07:35 UTC, merged